Update Jenkinsfile

diff --git a/analytics/Jenkinsfile b/analytics/Jenkinsfile
--- a/analytics/Jenkinsfile
+++ b/analytics/Jenkinsfile
@@ -1,3 +1,6 @@
+def nextVersion //x.y.z
+def Version //x.y
+
 pipeline {
     agent any
 
@@ -7,26 +10,26 @@ pipeline {
     }
 
     stages {
-        stage("Tag Calculate") {
-            when { branch "release/*" }
+        stage('calculate tag'){
+            when {
+                branch "release/*"
+            }
             steps {
                 script {
-                    sh "git fetch --tags"
-                    def tags = sh(script: "git tag --list --merged", returnStdout: true).trim()
-                    String lastTag
-                    if (tags) {
-                        lastTag = tags.split('\n').reverse()[0]
-                        env.VERSION = lastTag
-                    } else {
-                        lastTag = sh(script: "echo ${BRANCH_NAME} | cut -d'/' -f2", returnStdout: true).trim()
-                        env.VERSION = lastTag
-                        lastTag = lastTag + ".0"
-                    }
-                    def (major, minor, patch) = lastTag.split('\\.')
-                    def patchNum = 1
-                    patchNum += Integer.parseInt(patch)
-                    env.NEW_VERSION = "${major}.${minor}.${patchNum}"
-                    sh "mvn versions:set -DnewVersion=${NEW_VERSION}"
+                    sh 'git fetch --all --tags'
+                        Version = (env.GIT_BRANCH  =~ /(\d+\.\d+)$/)[0][1]
+                        def baseVersion = "${Version}"
+                        def lastVersion = sh(script: "git tag | grep '^${baseVersion}' | sort -V | tail -n 1", returnStdout: true).trim()
+                        println "Last version of ${baseVersion}: ${lastVersion}"
+                        if (lastVersion == "") {
+                            nextVersion = "${baseVersion}.0"
+                        } else {
+                            def versionParts = lastVersion.split("\\.")
+                            def lastVersionNumber = Integer.parseInt(versionParts[-1])
+                            nextVersion = "${baseVersion}.${lastVersionNumber + 1}"
+                        }
+                    sh "mvn versions:set -DnewVersion=${nextVersion}"
+                    sh "mvn versions:commit"
                 }
             }
         }
@@ -47,70 +50,52 @@ pipeline {
             }
         }
 
-        stage("Check Feature For E2E message") {
-            when { branch "feature/*" }
-            steps {
-                script{
-                def lastCommitMessage = sh(script: 'git log -1 --pretty=format:%s', returnStdout: true).trim()
-                echo "Last commit message: ${lastCommitMessage}"
-                if (lastCommitMessage.contains("#e2e")) {
-                    withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/'
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/'
-                }
-
-                   latest_simulator_snapshot= sh(returnStdout: true, script: 'ls -t simulator/99-SNAPSHOT/simulator-99*.jar | head -1').trim()
-                    latest_telemetry_snapshot= sh(returnStdout: true, script: 'ls -t telemetry/99-SNAPSHOT/telemetry-99*.jar | head -1').trim()
-                    sh "cp ${latest_telemetry_snapshot} telemetry.jar"
-                    sh "cp ${latest_simulator_snapshot} simulator.jar"
-                    sh "cp target/analytics-*.jar analytics.jar"
-                    sh "java -cp simulator.jar:telemetry.jar:analytics.jar com.lidar.simulation.Simulator"
-                    }
-                }
+        stage("e2e testing") {
+            when {
+                expression { return env.GIT_BRANCH =~ /^feature\/.*$/ || env.GIT_BRANCH == 'main' || env.GIT_BRANCH =~ /^release\/\d+\.\d+$/ }
             }
-        }
-
-        stage("E2E Tests (release)") {
-            when { anyOf { branch "release/*"} }
             steps {
-                script{
-                withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-release-local/com/lidar/telemetry/'
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/'
-                    
-                    telemetry_folder = sh(returnStdout: true, script: "cd ./telemetry/ && ls -d */ | grep ${env.VERSION} | head -1").trim()
-                    if (telemetry_folder == ""){
-                        error("telemetry and analytics versions do not match")
-                    }
-                    latest_telemetry_clean = sh(returnStdout: true, script:"basename ${telemetry_folder} '/'").trim()
-                    telemetry_path = "./telemetry/${latest_telemetry_clean}/telemetry-${latest_telemetry_clean}.jar"
-                    echo "telemetry ---> ${telemetry_path}"
+                    script {
+                        withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
+                        if (env.GIT_BRANCH =~ /^feature\/.*$/ ) {
+                            def lastCommitMessage = sh(script: 'git log -1 --pretty=format:%s', returnStdout: true).trim()
+                            if (lastCommitMessage.contains("#e2e")) {
+                                def latest_telemetry = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/ | grep -E \'analytics-[0-9\\.]+.*\\.jar<\' | sed "s/<[^>]\\+>//g" | cut -d " " -f 1 | sort -V -r | head -n 1', returnStdout: true).trim()
 
-                    simulator_path= sh(returnStdout: true, script: 'ls -t simulator/99-SNAPSHOT/simulator-99*.jar | head -1').trim()
-                    echo "simulator path ---> ${simulator_path}"
+                                sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/"${latest_telemetry}" --output telemetry.jar"""
+                                
+                                def latest_simulator = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/ | grep -E \'simulator-[0-9\\.]+.*\\.jar<\' | sed "s/<[^>]\\+>//g" | cut -d " " -f 1 | sort -V -r | head -n 1', returnStdout: true).trim()
+                                sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/"$latest_simulator" --output simulator.jar"""
 
-                    analytics_path = "./target/analytics-${NEW_VERSION}.jar"
-                    echo "analytics path ---> ${analytics_path}"
+                                sh "cp target/analytics-99-SNAPSHOT.jar ./analytics.jar"
+                                sh "java -cp analytics.jar:simulator.jar:telemetry.jar com.lidar.simulation.Simulator"
 
-                    sh "java -cp ${simulator_path}:${telemetry_path}:${analytics_path} com.lidar.simulation.Simulator"
-                    }
-                }
-            }
-        }
+                            } else {
+                                sh "echo 'NOT #e2e in commit message!'"
+                            }
+                        }
+                     if (env.GIT_BRANCH == 'main') {
+                            def latest_telemetry = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/ | grep -E \'telemetry-[0-9\\.]+.*\\.jar<\' | sed "s/<[^>]\\+>//g" | cut -d " " -f 1 | sort -V -r | head -n 1', returnStdout: true).trim()
+                            sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/"${latest_telemetry}" --output telemetry.jar"""
 
-        stage("E2E Tests (main)") {
-            when { anyOf { branch "main"} }
-            steps{
-                script{
-                    withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/telemetry/99-SNAPSHOT/'
-                    sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/'
-                        latest_simulator_snapshot= sh(returnStdout: true, script: 'ls -t simulator/99-SNAPSHOT/simulator-99*.jar | head -1').trim()
-                        latest_telemetry_snapshot= sh(returnStdout: true, script: 'ls -t telemetry/99-SNAPSHOT/telemetry-99*.jar | head -1').trim()
-                        sh "cp ${latest_telemetry_snapshot} telemetry.jar"
-                        sh "cp ${latest_simulator_snapshot} simulator.jar"
-                        sh "cp ./target/analytics-*.jar analytics.jar"
-                        sh "java -cp simulator.jar:telemetry.jar:analytics.jar com.lidar.simulation.Simulator"
+                            def latest_simulator = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/ | grep -E \'simulator-[0-9\\.]+.*\\.jar<\' | sed "s/<[^>]\\+>//g" | cut -d " " -f 1 | sort -V -r | head -n 1', returnStdout: true).trim()
+                            sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/"$latest_simulator" --output simulator.jar"""
+
+                            sh "cp target/analytics-99-SNAPSHOT.jar ./analytics.jar"
+                            sh "java -cp analytics.jar:simulator.jar:telemetry.jar com.lidar.simulation.Simulator"
+                        }
+
+                    if (env.GIT_BRANCH =~ /^release\/\d+\.\d+$/) {
+                        def latest_telemetry = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-release-local/com/lidar/telemetry/ | grep -oP \'(?<=<a href=")\\d+\\.\\d+\\.\\d+/\' | sed "s:/$::" | sort -V -r | head -n 1', returnStdout: true).trim()
+
+                        sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-release-local/com/lidar/telemetry/"${latest_telemetry}"/telemetry-"${latest_telemetry}".jar --output telemetry.jar"""
+
+                        def latest_simulator = sh (script: 'curl -s -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/ | grep -E \'simulator-[0-9\\.]+.*\\.jar<\' | sed "s/<[^>]\\+>//g" | cut -d " " -f 1 | sort -V -r | head -n 1', returnStdout: true).trim()
+
+                        sh """curl -u ${username}:${password} http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/"$latest_simulator" --output simulator.jar"""
+                        sh "cp target/analytics-${nextVersion}.jar ./analytics.jar"
+                        sh "java -cp analytics.jar:simulator.jar:telemetry.jar com.lidar.simulation.Simulator"
+                        }
                     }
                 }
             }
@@ -130,10 +115,22 @@ pipeline {
             steps {
                 withCredentials([usernamePassword(credentialsId: 'Gitlab-username-and-password', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                     sh 'git remote set-url origin "http://${GIT_USERNAME}:${GIT_PASSWORD}@gitlab/ofir-dev/analytics.git"'
-                    sh "git tag -a ${env.NEW_VERSION} -m '[ci-skip]'"
-                    sh "git push origin ${env.NEW_VERSION}"
+                    sh "git tag -a ${nextVersion} -m '[ci-skip]'"
+                    sh "git push origin ${nextVersion}"
                 }
             }
+        }
+    }
+    post{
+        always{
+            echo "========always========"
+            cleanWs()
+        }
+        success{
+            echo "========pipeline executed successfully ========"
+        }
+        failure{
+            echo "========pipeline execution failed========"
         }
     }
 }
